### ISSUE TITLE
Compile fails with PHP 8.4.4

### ISSUE THREAD

**Issue by buzanits** [php/pecl-mail-imap#16]
I tried to compile imap with
```
./configure --with-imap --with-imap-ssl --with-kerberos --libdir=/usr/lib64 --with-libdir=lib64
make
```
I get the follwing error (first lines)
```
In file included from /root/build/rpmbuild/BUILD/imap-1.0.3/php_imap.c:48:
/root/build/rpmbuild/BUILD/imap-1.0.3/php_imap.h:50:32: error: expected declaration specifiers or ‘...’ before string constant
   50 |  ZEND_DIAGNOSTIC_IGNORED_START("-Wstrict-prototypes")
      |                                ^~~~~~~~~~~~~~~~~~~~~

```
What is going wrong here? I add the full error output as a file.

[error.txt](https://github.com/user-attachments/files/18886252/error.txt)

**Comment by cmb69** [comment]
Looks like the `ZEND_DIAGNOSTIC_IGNORED_START` macro isn't properly resolved. Perhaps, zend_portability.h is not included for some reason.

What compiler are you using (including its version)?

**Comment by buzanits** [comment]
gcc version 11.5.0 20240719 (Red Hat 11.5.0-5) (GCC)

**Comment by cmb69** [comment]
Thanks! So nothing particular special. I'm at a loss, since a recent build against PHP 8.4.4 worked fine in CI (https://github.com/php/pecl-mail-imap/actions/runs/13202020165/job/37330509903).

Please provide some info about the way you've tried to build. Did you use `phpize`, or attempted an in-tree build? Maybe also attach your config.log.

**Comment by remicollet** [comment]
> gcc version 11.5.0 20240719 (Red Hat 11.5.0-5) (GCC)

@buzanits FYI, version **1.0.3** build fine with PHP **8.4.4** on
- RHEL 8.10 using default GCC 8.5
- RHEL 9.5 using default GCC 11.5
- RHEL-10.0-Beta using default GCC 14.2

P.S. used to build the RPMs available in my [repository](https://rpms.remirepo.net/)

**Comment by buzanits** [comment]
It seems that the Makefile tried to include `/usr/include/php` instead of the proper directory. Something must have been wrong with the `./configure` command I used. It works when I symlink the source to `/usr/include/php` but it would be better to be able to tell .configure to use a different include dir.

**Comment by graciano** [comment]
I have the same issue with imap-1.0.0. Currently I have an asdf php `8.1.31` installation, and ran `pecl download imap-1.0.0` and then the same `./configure` command as the original post to check why it wasn't installing normally.
